Trying to fix flaky test suite
aiidalab/aiidalab-launch pull request #164
Opened 2023-01-11 19:15 UTC by danielhollas

I was trying to hunt down the issue behing the GHA CI timeout failures, reported in #163. 

The hypothesis was to see if issue #154 was behind this. See my last comment on #154 for details about my investigation. One think I noticed is that the asyncio `echo_logs` Task would not get cancelled if the container failed to start. I don't know if this is the reason for the test flakiness, but it is worth a shot I think.

EDIT: So this obviously did not help, but it still seems like a change worth doing. I've also decreased the timeout on GHA so that at least we're not wasting CI minutes.

2023-01-11 19:55 UTC, danielhollas commented on aiidalab_launch/instance.py
> +            LOGGER.warning(f"Unable to pull image: {self.profile.image}")
`logging.warn` is deprecated, and we were getting a warning from pytest about this.

2023-01-16 10:26 UTC, yakutovicha requested changes
Thanks, @danielhollas.

One test keeps failing with an "out of runtime error". I suggest increasing the timeout to 15. Otherwise, good to go from my side.

2023-01-16 10:26 UTC, yakutovicha commented on .github/workflows/ci.yml
> +        timeout-minutes: 10
```suggestion
        timeout-minutes: 15
```

2023-01-16 12:01 UTC, danielhollas commented
> One test keeps failing with an "out of runtime error". I suggest increasing the timeout to 15. Otherwise, good to go from my side.

If you're referring to for example https://github.com/aiidalab/aiidalab-launch/actions/runs/3896105969/jobs/6698675263, yes, the test suite randomly times out for unknown reason, as reported in #163. I've increased it to 15 minutes but this will not solve the issue as it has been happening for some time even with 30 minutes. (the idea of decreasing the timeout was to fail early in those cases).

In the link above, there's a following pytest warning:

```python
=============================== warnings summary ===============================
tests/test_cli.py::TestInstanceLifecycle::test_start_stop_reset
  /opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py:641: RuntimeWarning: coroutine 'Queue.put' was never awaited
    self._ready.clear()
```

This points to perhaps that the issue #154 is behind these timeouts, see also my last comments on that issue where I tried to analyze where it is coming from. This prompted this PR, which obviously didn't fix the issue so more investigation is needed.

Sorry for not being clear in the OP.

2023-01-16 13:29 UTC, yakutovicha approved these changes
LGTM.

@danielhollas I let you merge it.

2023-01-19 11:16 UTC, merged

2023-01-19 11:17 UTC, yakutovicha commented
@danielhollas, please remind me next week (I am currently at a conference). I will give my more rights to the AiiDAlab organisation.